version: '3.8'

services:
  app:
    image: python:3.11
    container_name: my_python_app
    working_dir: /app
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
    command: uv pip install -r requirements.txt && python app.py
