version: "3.8"

services:
  app:
    image: python:3.11
    container_name: my_python_app
    working_dir: /app
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
    ports:
      - "8080:8080"
    command: >
      sh -c "pip install uv && uv venv .venv && uv pip install --system --requirements pyproject.toml && python app.py"
