version: "3.8"

services:
  app:
    image: python:3.11
    container_name: my_python_app
    working_dir: /app
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
    ports:
      - "8080:8080"
    depends_on:
      - postgres-primary
      - postgres-replica
    command: >
      sh -c "pip install uv && uv venv .venv && uv pip install --system --requirements pyproject.toml && python app.py"

  postgres-primary:
    image: postgres:15
    container_name: postgres-primary
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
      POSTGRES_REPLICATION_USER: repl_user
      POSTGRES_REPLICATION_PASSWORD: repl_password
    ports:
      - "5432:5432"
    volumes:
      - pg_primary_data:/var/lib/postgresql/data
    command: >
      bash -c "
        echo 'host replication repl_user 0.0.0.0/0 md5' >> /var/lib/postgresql/data/pg_hba.conf &&
        chown -R postgres:postgres /var/lib/postgresql/data &&
        chmod 700 /var/lib/postgresql/data &&
        exec postgres -D /var/lib/postgresql/data -c config_file=/var/lib/postgresql/data/postgresql.conf
      "

  postgres-replica:
    image: postgres:15
    container_name: postgres-replica
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
      POSTGRES_REPLICATION_USER: repl_user
      POSTGRES_REPLICATION_PASSWORD: repl_password
    ports:
      - "5433:5432"
    depends_on:
      - postgres-primary
    volumes:
      - pg_replica_data:/var/lib/postgresql/data
    command: >
      bash -c "
        until pg_isready -h postgres-primary -p 5432 -U repl_user; do sleep 2; done;
        rm -rf /var/lib/postgresql/data/* &&
        PGPASSWORD=repl_password pg_basebackup -h postgres-primary -U repl_user -D /var/lib/postgresql/data -Fp -Xs -P -R &&
        touch /var/lib/postgresql/data/standby.signal &&
        echo 'primary_conninfo = \"host=postgres-primary port=5432 user=repl_user password=repl_password\"' >> /var/lib/postgresql/data/postgresql.conf &&
        chown -R postgres:postgres /var/lib/postgresql/data &&
        chmod 700 /var/lib/postgresql/data &&
        exec postgres -D /var/lib/postgresql/data
      "

volumes:
  pg_primary_data:
  pg_replica_data:
