global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-primary:9187', 'postgres-replica-1:9187', 'postgres-replica-2:9187', 'postgres-replica-3:9187']

  - job_name: 'haproxy'
    static_configs:
      - targets: ['haproxy:8404']
